# Generated by Django 5.1.6 on 2025-03-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=10, unique=True)),
                ("course_name", models.CharField(max_length=100)),
                ("credits", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("instructor", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
